version: '2.4'

services:

  sql:
    image: sitecore-xp-sqldev:9.1.1-windowsservercore-${windows_version}
    volumes:
      - .\data\sql:C:\Data
    mem_limit: 2GB
    ports:
      - "44010:1433"

  solr:
    image: sitecore-xp-solr:9.1.1-nanoserver-${windows_version}
    volumes:
      - .\data\solr:C:\Data
    mem_limit: 1GB
    ports:
      - "44011:8983"
  
  xconnect:
    image: sitecore-xp-xconnect:9.1.1-windowsservercore-${windows_version}
    volumes:
      - .\data\xconnect:C:\inetpub\xconnect\App_Data\logs
    mem_limit: 1GB
    links:
      - sql
      - solr

  xconnect-automationengine:
    image: sitecore-xp-xconnect-automationengine:9.1.1-windowsservercore-${windows_version}
    volumes:
      - .\data\xconnect-automationengine:C:\AutomationEngine\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - xconnect

  xconnect-indexworker:
    image: sitecore-xp-xconnect-indexworker:9.1.1-windowsservercore-${windows_version}
    volumes:
      - .\data\xconnect-indexworker:C:\IndexWorker\App_Data\logs
    mem_limit: 500MB
    links:
      - sql
      - solr

  cd:
    build:
      context: .\src\MessageBusSample
      dockerfile: Dockerfile.cd
    volumes:
      - .\data\cd:C:\inetpub\sc\App_Data\logs
    ports:
      - "44002:80"
    links:
      - sql
      - solr
      - xconnect

  cm:
    build:
      context: .\src\MessageBusSample
      dockerfile: Dockerfile.cm
    volumes:
      - .\data\cm:C:\inetpub\sc\App_Data\logs
    ports:
      - "44001:80"
    links:
      - sql
      - solr
      - xconnect