#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see http://aka.ms/containercompat 

FROM implicit/sitecore-xm1-cd:9.1.1-windowsservercore-ltsc2019
ARG source

WORKDIR /inetpub/sc

COPY ${source:-obj/Docker/publish}/bin/MessageBus.CD.dll ./bin

EXPOSE 80